"""update table RoleLock yaa

Revision ID: 0a74a89b66b3
Revises: 50a0c1a65b85
Create Date: 2025-05-21 20:47:46.185013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a74a89b66b3'
down_revision: Union[str, None] = '50a0c1a65b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lock_system_created_by_fkey', 'lock_system', type_='foreignkey')
    op.drop_column('lock_system', 'created_by')
    op.drop_column('lock_system', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lock_system', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('lock_system', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('lock_system_created_by_fkey', 'lock_system', 'user', ['created_by'], ['user_id'])
    # ### end Alembic commands ###
