"""Updated employee model

Revision ID: 110013f7a141
Revises: 8077725e503e
Create Date: 2025-04-26 17:33:33.608516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '110013f7a141'
down_revision: Union[str, None] = '8077725e503e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'employees', 
        'face_encoding', 
        type_=sa.LargeBinary(), 
        existing_type=sa.Text(),
        postgresql_using='face_encoding::bytea'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'face_encoding',
               existing_type=sa.LargeBinary(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
