"""rebuild attendance model

Revision ID: 2ca96322a26c
Revises: 97c6cd6f6841
Create Date: 2025-05-20 14:20:06.651642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca96322a26c'
down_revision: Union[str, None] = '97c6cd6f6841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('clock_in_distance', sa.Float(), nullable=True))
    op.add_column('attendance', sa.Column('clock_out_distance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'clock_out_distance')
    op.drop_column('attendance', 'clock_in_distance')
    # ### end Alembic commands ###
