"""update table RoleLock yaaaaa

Revision ID: 37187f8c4845
Revises: ea61e49edaa7
Create Date: 2025-05-21 21:46:10.959329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37187f8c4845'
down_revision: Union[str, None] = 'ea61e49edaa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lock_system_locked_by_fkey', 'lock_system', type_='foreignkey')
    op.drop_column('lock_system', 'locked_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lock_system', sa.Column('locked_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('lock_system_locked_by_fkey', 'lock_system', 'user', ['locked_by'], ['user_id'])
    # ### end Alembic commands ###
