"""nisa

Revision ID: 3901a16151d1
Revises: 6ec3a74d4eec
Create Date: 2025-05-19 02:57:00.048059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3901a16151d1'
down_revision: Union[str, None] = '6ec3a74d4eec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'permissions', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_column('permissions', 'user_id')
    # ### end Alembic commands ###
