"""rebuild attendance model

Revision ID: 4c512bb7bcad
Revises: 3e177493457f
Create Date: 2025-05-20 14:21:34.061294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c512bb7bcad'
down_revision: Union[str, None] = '3e177493457f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('clock_in', sa.Time(), nullable=True),
    sa.Column('clock_in_latitude', sa.Float(), nullable=True),
    sa.Column('clock_in_longitude', sa.Float(), nullable=True),
    sa.Column('clock_in_verified', sa.Boolean(), nullable=True),
    sa.Column('clock_in_reason', sa.Text(), nullable=True),
    sa.Column('clock_in_distance', sa.Float(), nullable=True),
    sa.Column('clock_out', sa.Time(), nullable=True),
    sa.Column('clock_out_latitude', sa.Float(), nullable=True),
    sa.Column('clock_out_longitude', sa.Float(), nullable=True),
    sa.Column('clock_out_verified', sa.Boolean(), nullable=True),
    sa.Column('clock_out_reason', sa.Text(), nullable=True),
    sa.Column('clock_out_distance', sa.Float(), nullable=True),
    sa.Column('attendance_date', sa.Date(), nullable=True),
    sa.Column('attendance_status', sa.String(length=20), nullable=True),
    sa.Column('face_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('attendance_id')
    )
    op.create_index(op.f('ix_attendance_attendance_id'), 'attendance', ['attendance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_attendance_id'), table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###
