"""update table RoleLock ya

Revision ID: 50a0c1a65b85
Revises: 155f9fa2489e
Create Date: 2025-05-21 20:26:31.975191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a0c1a65b85'
down_revision: Union[str, None] = '155f9fa2489e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lock_system', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('lock_system', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'lock_system', 'user', ['created_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lock_system', type_='foreignkey')
    op.drop_column('lock_system', 'created_at')
    op.drop_column('lock_system', 'created_by')
    # ### end Alembic commands ###
