"""update table RoleLock

Revision ID: 679237881108
Revises: 4c512bb7bcad
Create Date: 2025-05-20 21:20:38.747581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '679237881108'
down_revision: Union[str, None] = '4c512bb7bcad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lock_system', sa.Column('rolesid', sa.Integer(), nullable=True))
    op.drop_constraint('lock_system_role_id_fkey', 'lock_system', type_='foreignkey')
    op.create_foreign_key(None, 'lock_system', 'roles', ['rolesid'], ['roles_id'])
    op.drop_column('lock_system', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lock_system', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lock_system', type_='foreignkey')
    op.create_foreign_key('lock_system_role_id_fkey', 'lock_system', 'roles', ['role_id'], ['roles_id'])
    op.drop_column('lock_system', 'rolesid')
    # ### end Alembic commands ###
