"""attendance update

Revision ID: 6ec3a74d4eec
Revises: 6b95a99d02c8
Create Date: 2025-05-18 12:42:13.044169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ec3a74d4eec'
down_revision: Union[str, None] = '6b95a99d02c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('clock_in_latitude', sa.Float(), nullable=True))
    op.add_column('attendance', sa.Column('clock_in_longitude', sa.Float(), nullable=True))
    op.add_column('attendance', sa.Column('clock_in_verified', sa.Boolean(), nullable=True))
    op.add_column('attendance', sa.Column('clock_in_reason', sa.Text(), nullable=True))
    op.add_column('attendance', sa.Column('clock_out_latitude', sa.Float(), nullable=True))
    op.add_column('attendance', sa.Column('clock_out_longitude', sa.Float(), nullable=True))
    op.add_column('attendance', sa.Column('clock_out_verified', sa.Boolean(), nullable=True))
    op.add_column('attendance', sa.Column('clock_out_reason', sa.Text(), nullable=True))
    op.add_column('attendance', sa.Column('face_verified', sa.Boolean(), nullable=True))
    op.alter_column('attendance', 'attendance_status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'attendance_status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_column('attendance', 'face_verified')
    op.drop_column('attendance', 'clock_out_reason')
    op.drop_column('attendance', 'clock_out_verified')
    op.drop_column('attendance', 'clock_out_longitude')
    op.drop_column('attendance', 'clock_out_latitude')
    op.drop_column('attendance', 'clock_in_reason')
    op.drop_column('attendance', 'clock_in_verified')
    op.drop_column('attendance', 'clock_in_longitude')
    op.drop_column('attendance', 'clock_in_latitude')
    # ### end Alembic commands ###
