"""Extend description length

Revision ID: 8978809de49f
Revises: badc36fd4cc9
Create Date: 2025-05-27 03:07:46.995844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8978809de49f'
down_revision: Union[str, None] = 'badc36fd4cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('activity_logs', 'device',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_logs', 'device',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('activity_logs', 'ip_address',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=45),
               existing_nullable=True)
    # ### end Alembic commands ###
