"""add face encoding

Revision ID: 97c6cd6f6841
Revises: e0cf9a061c37
Create Date: 2025-05-19 15:48:12.775429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c6cd6f6841'
down_revision: Union[str, None] = 'e0cf9a061c37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('face_encoding', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'face_encoding')
    # ### end Alembic commands ###
