"""update

Revision ID: 9b439f83dee9
Revises: cf51bc20a741
Create Date: 2025-07-26 22:53:12.814242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b439f83dee9'
down_revision: Union[str, None] = 'cf51bc20a741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lock_system', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_lock_system_lock_id'), 'lock_system', ['lock_id'], unique=False)
    op.drop_column('lock_system', 'start_date')
    op.drop_column('lock_system', 'end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lock_system', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('lock_system', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_lock_system_lock_id'), table_name='lock_system')
    op.alter_column('lock_system', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
