"""update role lockkkk

Revision ID: bbe46a5a2e13
Revises: 7cc42934dbcd
Create Date: 2025-06-17 22:31:14.069964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe46a5a2e13'
down_revision: Union[str, None] = '7cc42934dbcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lock_system', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.add_column('lock_system', sa.Column('end_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lock_system', sa.Column('is_locked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('lock_system', 'end_date')
    op.drop_column('lock_system', 'start_date')
    # ### end Alembic commands ###
