"""delete face encoding

Revision ID: e0cf9a061c37
Revises: 9ecbde6723a4
Create Date: 2025-05-19 15:47:54.256383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0cf9a061c37'
down_revision: Union[str, None] = '9ecbde6723a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'face_encoding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('face_encoding', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
