"""update logs model

Revision ID: e7bd1d180a89
Revises: d0f5994d2dbf
Create Date: 2025-05-03 20:03:10.205181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7bd1d180a89'
down_revision: Union[str, None] = 'd0f5994d2dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('log_id', sa.Integer(), nullable=False))
    op.drop_index('ix_activity_logs_id', table_name='activity_logs')
    op.create_index(op.f('ix_activity_logs_log_id'), 'activity_logs', ['log_id'], unique=False)
    op.drop_column('activity_logs', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_activity_logs_log_id'), table_name='activity_logs')
    op.create_index('ix_activity_logs_id', 'activity_logs', ['id'], unique=False)
    op.drop_column('activity_logs', 'log_id')
    # ### end Alembic commands ###
