"""update table RoleLock yaaaa

Revision ID: ea61e49edaa7
Revises: 0a74a89b66b3
Create Date: 2025-05-21 21:41:55.339824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea61e49edaa7'
down_revision: Union[str, None] = '0a74a89b66b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lock_system', sa.Column('locked_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'lock_system', 'user', ['locked_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lock_system', type_='foreignkey')
    op.drop_column('lock_system', 'locked_by')
    # ### end Alembic commands ###
