"""update table RoleLockkk

Revision ID: f4ca5698629c
Revises: 9dfd6eaee8ee
Create Date: 2025-05-20 21:23:02.544274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ca5698629c'
down_revision: Union[str, None] = '9dfd6eaee8ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lock_system', sa.Column('roles_id', sa.Integer(), nullable=True))
    op.drop_constraint('lock_system_rolesid_fkey', 'lock_system', type_='foreignkey')
    op.create_foreign_key(None, 'lock_system', 'roles', ['roles_id'], ['roles_id'])
    op.drop_column('lock_system', 'rolesid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lock_system', sa.Column('rolesid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lock_system', type_='foreignkey')
    op.create_foreign_key('lock_system_rolesid_fkey', 'lock_system', 'roles', ['rolesid'], ['roles_id'])
    op.drop_column('lock_system', 'roles_id')
    # ### end Alembic commands ###
