"""update table RoleLock bun

Revision ID: fb11278f9292
Revises: f4ca5698629c
Create Date: 2025-05-20 21:29:57.842096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb11278f9292'
down_revision: Union[str, None] = 'f4ca5698629c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lock_system', sa.Column('role_id', sa.Integer(), nullable=True))
    op.drop_constraint('lock_system_roles_id_fkey', 'lock_system', type_='foreignkey')
    op.create_foreign_key(None, 'lock_system', 'roles', ['role_id'], ['roles_id'])
    op.drop_column('lock_system', 'roles_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lock_system', sa.Column('roles_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lock_system', type_='foreignkey')
    op.create_foreign_key('lock_system_roles_id_fkey', 'lock_system', 'roles', ['roles_id'], ['roles_id'])
    op.drop_column('lock_system', 'role_id')
    # ### end Alembic commands ###
